import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE_DIR = path.join(ROOT_DIR, 'i18n', 'source')
const LOCALES_DIR = path.join(ROOT_DIR, 'public', '_locales')
const GENERATED_TS_PATH = path.join(ROOT_DIR, 'src', 'shared', 'lib', 'i18n.generated.ts')
const DEFAULT_LOCALE = 'en'
const MESSAGE_KEY_PATTERN = /^[a-z0-9_]+$/

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function flattenMessages(value, pathSegments = [], result = {}) {
  if (!isPlainObject(value)) {
    throw new Error(`Expected an object at "${pathSegments.join('.') || '<root>'}"`)
  }

  for (const [key, nestedValue] of Object.entries(value)) {
    const nextPath = [...pathSegments, key]

    if (typeof nestedValue === 'string') {
      const messageKey = nextPath.join('_')

      if (!MESSAGE_KEY_PATTERN.test(messageKey)) {
        throw new Error(
          `Invalid message key "${messageKey}". Use lowercase letters, numbers, and underscores only.`,
        )
      }

      if (messageKey in result) {
        throw new Error(`Duplicate message key "${messageKey}"`)
      }

      result[messageKey] = nestedValue
      continue
    }

    if (!isPlainObject(nestedValue)) {
      throw new Error(`Expected a string or nested object at "${nextPath.join('.')}"`)
    }

    flattenMessages(nestedValue, nextPath, result)
  }

  return result
}

function getMissingKeys(referenceKeys, localeKeys) {
  return referenceKeys.filter((key) => !localeKeys.includes(key))
}

function getExtraKeys(referenceKeys, localeKeys) {
  return localeKeys.filter((key) => !referenceKeys.includes(key))
}

async function readSourceLocales() {
  const localeFiles = (await fs.readdir(SOURCE_DIR))
    .filter((fileName) => fileName.endsWith('.json'))
    .sort()

  if (localeFiles.length === 0) {
    throw new Error('No source locale files found in i18n/source')
  }

  const locales = new Map()

  for (const fileName of localeFiles) {
    const locale = path.basename(fileName, '.json')
    const filePath = path.join(SOURCE_DIR, fileName)
    const source = JSON.parse(await fs.readFile(filePath, 'utf8'))
    locales.set(locale, flattenMessages(source))
  }

  return locales
}

const PLACEHOLDER_NAMES = ['value', 'value2', 'value3', 'value4', 'value5']

async function writeChromeLocales(locales) {
  await fs.mkdir(LOCALES_DIR, { recursive: true })
  const existingLocaleEntries = await fs.readdir(LOCALES_DIR, { withFileTypes: true })

  await Promise.all(
    existingLocaleEntries
      .filter((entry) => entry.isDirectory() && !locales.has(entry.name))
      .map((entry) => fs.rm(path.join(LOCALES_DIR, entry.name), { force: true, recursive: true })),
  )

  await Promise.all(
    [...locales.entries()].map(async ([locale, messages]) => {
      const localeDir = path.join(LOCALES_DIR, locale)
      const chromeMessages = Object.fromEntries(
        Object.entries(messages).map(([key, message]) => {
          const indices = [...new Set([...message.matchAll(/\$(\d+)/g)].map(([, n]) => Number(n)))]

          if (indices.length === 0) {
            return [key, { message }]
          }

          let chromeMessage = message
          const placeholders = {}

          for (const index of indices) {
            const name = PLACEHOLDER_NAMES[index - 1]
            chromeMessage = chromeMessage.replaceAll(`$${index}`, `$${name.toUpperCase()}$`)
            placeholders[name] = { content: `$${index}` }
          }

          return [key, { message: chromeMessage, placeholders }]
        }),
      )

      await fs.mkdir(localeDir, { recursive: true })
      await fs.writeFile(
        path.join(localeDir, 'messages.json'),
        `${JSON.stringify(chromeMessages, null, 2)}\n`,
      )
    }),
  )
}

async function writeGeneratedTypes(referenceMessages) {
  const generatedSource = `// This file is auto-generated by scripts/generate-locales.mjs.\n// Do not edit manually.\n\nexport const DEFAULT_MESSAGES = ${JSON.stringify(
    referenceMessages,
    null,
    2,
  )} as const\n\nexport type MessageKey = keyof typeof DEFAULT_MESSAGES\nexport const MESSAGE_KEYS = Object.keys(DEFAULT_MESSAGES) as MessageKey[]\n`

  await fs.writeFile(GENERATED_TS_PATH, generatedSource)
}

async function main() {
  const locales = await readSourceLocales()
  const referenceMessages = locales.get(DEFAULT_LOCALE)

  if (!referenceMessages) {
    throw new Error(`Missing default locale "${DEFAULT_LOCALE}"`)
  }

  const referenceKeys = Object.keys(referenceMessages).sort()

  for (const [locale, messages] of locales.entries()) {
    const localeKeys = Object.keys(messages).sort()
    const missingKeys = getMissingKeys(referenceKeys, localeKeys)
    const extraKeys = getExtraKeys(referenceKeys, localeKeys)

    if (missingKeys.length > 0 || extraKeys.length > 0) {
      const parts = []

      if (missingKeys.length > 0) {
        parts.push(`missing keys: ${missingKeys.join(', ')}`)
      }

      if (extraKeys.length > 0) {
        parts.push(`extra keys: ${extraKeys.join(', ')}`)
      }

      throw new Error(`Locale "${locale}" does not match "${DEFAULT_LOCALE}" (${parts.join('; ')})`)
    }
  }

  await writeChromeLocales(locales)
  await writeGeneratedTypes(referenceMessages)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
})
